version: 2.4
jobs:
  build:
    docker:
      - image: node:v18.13.0
    environment:
      COVERALLS_REPO_TOKEN:
    working_directory: 
    steps:
      - checkout:
          path: 
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: 
      - run:
          name: 
          command: 